name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps
      - run: npm run lint                

      - run: npx playwright install --with-deps
      - run: npx playwright test --reporter=line
      - run: npm run test
      - run: npm run e2e
      - run: npm run coverage
      - run: npm run coverage:check
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
