name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Prepare coverage directory
        run: |
          mkdir -p coverage/tmp
          touch coverage/tmp/.keep

      - name: Validate coverage directory
        run: |
          if [ ! -d coverage/tmp ]; then
            echo "coverage/tmp directory does not exist. Recreating..."
            mkdir -p coverage/tmp
          fi

      - name: Run unit tests + coverage
        run: npm run coverage

      - name: Check coverage thresholds
        run: npm run coverage:check